"""Orchestrator coordinating the streaming pipeline.

Wires together: EmbeddingStore → LLMService (streaming) → TTSEngine
(chunked) → AvatarEngine (chunked) and exposes an async generator that
yields ``StreamEvent`` objects for progressive delivery via SSE.
"""

from __future__ import annotations

import re
import time
import traceback
import uuid
from pathlib import Path
from typing import AsyncIterator

from backend.app.avatar_engine import AvatarEngine
from backend.app.chunking import ChunkingModule
from backend.app.config import AppConfig
from backend.app.embedding_store import EmbeddingStore
from backend.app.llm_service import LLMService
from backend.app.logging_utils import get_logger, set_correlation_id
from backend.app.models import AvatarProfile, ProcessingStage, StreamEvent
from backend.app.pdf_parser import PDFParser
from backend.app.tts_engine import TTSEngine

logger = get_logger("orchestrator")

# Sentence boundary regex: split after . ! or ? followed by whitespace or end.
_SENTENCE_END = re.compile(r"(?<=[.!?])(?:\s|$)")


class Orchestrator:
    """Central coordinator for the streaming avatar pipeline.

    Lazily initialises heavy sub-components on first use so that
    construction is cheap and testable.

    Parameters
    ----------
    config:
        Application configuration.
    """

    def __init__(self, config: AppConfig) -> None:
        self._config = config

        # Lazy-init placeholders
        self._embedding_store: EmbeddingStore | None = None
        self._llm_service: LLMService | None = None
        self._tts_engine: TTSEngine | None = None
        self._avatar_engine: AvatarEngine | None = None
        self._pdf_parser: PDFParser | None = None
        self._chunking: ChunkingModule | None = None

        # In-memory avatar profile store keyed by avatar_id
        self._avatars: dict[str, AvatarProfile] = {}

    # ------------------------------------------------------------------
    # Lazy component accessors
    # ------------------------------------------------------------------

    @property
    def embedding_store(self) -> EmbeddingStore:
        if self._embedding_store is None:
            logger.info("Initialising EmbeddingStore")
            self._embedding_store = EmbeddingStore(
                collection_name="documents",
                persist_directory=self._config.chroma_persist_dir,
                embedding_model=self._config.embedding_model,
            )
        return self._embedding_store

    @property
    def llm_service(self) -> LLMService:
        if self._llm_service is None:
            logger.info("Initialising LLMService")
            self._llm_service = LLMService(config=self._config)
        return self._llm_service

    @property
    def tts_engine(self) -> TTSEngine:
        if self._tts_engine is None:
            logger.info("Initialising TTSEngine")
            self._tts_engine = TTSEngine(config=self._config)
        return self._tts_engine

    @property
    def avatar_engine(self) -> AvatarEngine:
        if self._avatar_engine is None:
            logger.info("Initialising AvatarEngine")
            self._avatar_engine = AvatarEngine(config=self._config)
        return self._avatar_engine

    @property
    def pdf_parser(self) -> PDFParser:
        if self._pdf_parser is None:
            logger.info("Initialising PDFParser")
            self._pdf_parser = PDFParser(config=self._config)
        return self._pdf_parser

    @property
    def chunking(self) -> ChunkingModule:
        if self._chunking is None:
            logger.info("Initialising ChunkingModule")
            self._chunking = ChunkingModule(config=self._config)
        return self._chunking

    # ------------------------------------------------------------------
    # Avatar upload
    # ------------------------------------------------------------------

    async def upload_avatar(
        self, file_path: str | Path, avatar_id: str | None = None
    ) -> AvatarProfile:
        """Validate and preprocess an avatar image.

        Parameters
        ----------
        file_path:
            Path to the uploaded image file.
        avatar_id:
            Optional caller-supplied avatar ID.  When provided the
            profile is stored under this key instead of the one
            generated by the avatar engine.

        Returns
        -------
        AvatarProfile
            The preprocessed profile (also stored in memory).
        """
        start = time.monotonic()
        logger.info(
            "upload_avatar started – file=%s, avatar_id=%s",
            file_path,
            avatar_id,
        )

        profile = self.avatar_engine.preprocess(str(file_path))
        # Use caller-supplied avatar_id when provided so the API layer
        # controls the identifier returned to the client.
        if avatar_id is not None:
            profile = AvatarProfile(
                avatar_id=avatar_id,
                image_path=profile.image_path,
                landmarks=profile.landmarks,
                preprocessed_at=profile.preprocessed_at,
            )
        self._avatars[profile.avatar_id] = profile

        duration_ms = (time.monotonic() - start) * 1000
        logger.info(
            "upload_avatar completed – avatar_id=%s, duration_ms=%.1f",
            profile.avatar_id,
            duration_ms,
        )
        return profile

    # ------------------------------------------------------------------
    # PDF upload
    # ------------------------------------------------------------------

    async def upload_pdf(
        self, file_path: str | Path, document_id: str | None = None
    ) -> dict:
        """Parse, chunk, and embed a PDF document.

        Parameters
        ----------
        file_path:
            Path to the uploaded PDF file.
        document_id:
            Optional caller-supplied document ID.  When ``None`` a
            random ID is generated.

        Returns
        -------
        dict
            ``{document_id, name, page_count, chunk_count}``
        """
        start = time.monotonic()
        if document_id is None:
            document_id = uuid.uuid4().hex[:12]
        file_path_str = str(file_path)
        name = Path(file_path_str).name
        logger.info(
            "upload_pdf started – file=%s, document_id=%s",
            file_path_str,
            document_id,
        )

        parsed = self.pdf_parser.parse(file_path_str)
        chunks = self.chunking.chunk(parsed, document_id=document_id)
        self.embedding_store.add_chunks(chunks)

        duration_ms = (time.monotonic() - start) * 1000
        logger.info(
            "upload_pdf completed – document_id=%s, pages=%d, chunks=%d, duration_ms=%.1f",
            document_id,
            parsed.page_count,
            len(chunks),
            duration_ms,
        )

        return {
            "document_id": document_id,
            "name": name,
            "page_count": parsed.page_count,
            "chunk_count": len(chunks),
        }

    # ------------------------------------------------------------------
    # Streaming question pipeline
    # ------------------------------------------------------------------

    async def process_question_stream(
        self, question: str, avatar_id: str
    ) -> AsyncIterator[StreamEvent]:
        """Execute the full streaming pipeline and yield events.

        Pipeline stages:
        1. Retrieve context from EmbeddingStore
        2. Stream tokens from LLMService
        3. Accumulate tokens into sentences
        4. Synthesize each sentence via TTSEngine
        5. Animate each audio chunk via AvatarEngine
        6. Yield StreamEvents throughout

        Yields
        ------
        StreamEvent
            Events of type ``text_token``, ``audio_chunk``,
            ``video_chunk``, ``stage_update``, ``error``, or ``done``.
        """
        correlation_id = uuid.uuid4().hex[:16]
        set_correlation_id(correlation_id)
        pipeline_start = time.monotonic()

        logger.info(
            "process_question_stream started – question=%r, avatar_id=%s",
            question,
            avatar_id,
        )

        try:
            # --- Validate avatar ---
            profile = self._avatars.get(avatar_id)
            if profile is None:
                yield StreamEvent(
                    type="error",
                    data={"message": f"Avatar '{avatar_id}' not found."},
                )
                return

            # --- Stage 1: Retrieval ---
            stage_start = time.monotonic()
            yield StreamEvent(
                type="stage_update",
                data={"stage": "retrieving", "status": "started"},
            )

            context = self.embedding_store.search(
                question, top_k=self._config.retrieval_top_k
            )

            retrieval_ms = (time.monotonic() - stage_start) * 1000
            yield StreamEvent(
                type="stage_update",
                data={
                    "stage": "retrieving",
                    "status": "completed",
                    "duration_ms": round(retrieval_ms, 1),
                },
            )
            logger.info("Retrieval completed – %d results, %.1f ms", len(context), retrieval_ms)

            # --- Stage 2: Streaming generation ---
            stage_start = time.monotonic()
            yield StreamEvent(
                type="stage_update",
                data={"stage": "generating", "status": "started"},
            )

            sentence_buffer = ""
            full_answer = ""
            chunk_index = 0
            stages: list[ProcessingStage] = []

            for token in self.llm_service.generate_stream(question, context):
                if token is None:
                    continue

                full_answer += token
                sentence_buffer += token

                # Yield each token immediately for progressive text display
                yield StreamEvent(
                    type="text_token",
                    data={"token": token},
                )

                # Check for sentence boundaries
                sentences = _split_sentences(sentence_buffer)
                if len(sentences) > 1:
                    # All but the last element are complete sentences
                    for sentence in sentences[:-1]:
                        sentence = sentence.strip()
                        if not sentence:
                            continue

                        # --- Synthesize audio chunk ---
                        async for event in self._synthesize_and_animate(
                            sentence, profile, chunk_index, correlation_id
                        ):
                            yield event
                        chunk_index += 1

                    # Keep the incomplete tail in the buffer
                    sentence_buffer = sentences[-1]

            # Flush remaining buffer as the final sentence
            remaining = sentence_buffer.strip()
            if remaining:
                async for event in self._synthesize_and_animate(
                    remaining, profile, chunk_index, correlation_id
                ):
                    yield event
                chunk_index += 1

            generation_ms = (time.monotonic() - stage_start) * 1000
            yield StreamEvent(
                type="stage_update",
                data={
                    "stage": "generating",
                    "status": "completed",
                    "duration_ms": round(generation_ms, 1),
                },
            )
            logger.info("Generation completed – %.1f ms", generation_ms)

            # --- Sources ---
            if context:
                yield StreamEvent(
                    type="sources",
                    data={
                        "sources": [
                            {
                                "chunk_text": r.chunk.text[:200],
                                "page": r.chunk.page_number,
                                "score": round(r.score, 4),
                            }
                            for r in context
                        ]
                    },
                )

            # --- Done ---
            total_ms = (time.monotonic() - pipeline_start) * 1000
            yield StreamEvent(
                type="done",
                data={"total_duration_ms": round(total_ms, 1)},
            )
            logger.info(
                "process_question_stream completed – total_duration_ms=%.1f",
                total_ms,
            )

        except Exception:
            tb = traceback.format_exc()
            logger.error("Unhandled exception in pipeline:\n%s", tb)
            yield StreamEvent(
                type="error",
                data={
                    "message": "An internal error occurred while processing your question. Please try again.",
                },
            )

    # ------------------------------------------------------------------
    # Internal: synthesize + animate a single sentence chunk
    # ------------------------------------------------------------------

    async def _synthesize_and_animate(
        self,
        sentence: str,
        profile: AvatarProfile,
        chunk_index: int,
        correlation_id: str,
    ) -> AsyncIterator[StreamEvent]:
        """Synthesize audio and animate video for one sentence chunk."""
        media_dir = Path(self._config.media_output_dir) / correlation_id
        media_dir.mkdir(parents=True, exist_ok=True)

        # --- TTS ---
        tts_start = time.monotonic()
        yield StreamEvent(
            type="stage_update",
            data={"stage": "synthesizing", "status": "started", "chunk_index": chunk_index},
        )

        audio_path = str(media_dir / f"audio_{chunk_index}.wav")
        audio_result = self.tts_engine.synthesize_chunk(sentence, audio_path)

        tts_ms = (time.monotonic() - tts_start) * 1000
        audio_web_url = "/api/data/" + str(Path(audio_result.file_path).relative_to("data"))
        yield StreamEvent(
            type="audio_chunk",
            data={
                "chunk_url": audio_web_url,
                "chunk_index": chunk_index,
                "duration_seconds": audio_result.duration_seconds,
            },
        )
        yield StreamEvent(
            type="stage_update",
            data={
                "stage": "synthesizing",
                "status": "completed",
                "chunk_index": chunk_index,
                "duration_ms": round(tts_ms, 1),
            },
        )
        logger.info(
            "TTS chunk %d completed – %.1f ms, %.2fs audio",
            chunk_index,
            tts_ms,
            audio_result.duration_seconds,
        )

        # --- Avatar animation ---
        anim_start = time.monotonic()
        yield StreamEvent(
            type="stage_update",
            data={"stage": "animating", "status": "started", "chunk_index": chunk_index},
        )

        video_path = str(media_dir / f"video_{chunk_index}.mp4")
        video_result = self.avatar_engine.animate_chunk(
            profile=profile,
            audio_path=audio_path,
            output_path=video_path,
            chunk_index=chunk_index,
        )

        anim_ms = (time.monotonic() - anim_start) * 1000
        video_web_url = "/api/data/" + str(Path(video_result.file_path).relative_to("data"))
        yield StreamEvent(
            type="video_chunk",
            data={
                "chunk_url": video_web_url,
                "chunk_index": chunk_index,
                "duration_seconds": video_result.duration_seconds,
            },
        )
        yield StreamEvent(
            type="stage_update",
            data={
                "stage": "animating",
                "status": "completed",
                "chunk_index": chunk_index,
                "duration_ms": round(anim_ms, 1),
            },
        )
        logger.info(
            "Animation chunk %d completed – %.1f ms, %.2fs video",
            chunk_index,
            anim_ms,
            video_result.duration_seconds,
        )


# ------------------------------------------------------------------
# Module-level helpers
# ------------------------------------------------------------------


def _split_sentences(text: str) -> list[str]:
    """Split *text* on sentence-ending punctuation (.!?).

    Returns a list where all elements except the last are complete
    sentences.  The last element is the remaining (possibly incomplete)
    buffer.
    """
    parts = _SENTENCE_END.split(text)
    # re.split may produce empty strings; filter them but keep the last
    # element even if empty (it represents the ongoing buffer).
    if not parts:
        return [text]
    return parts
